#!/bin/bash
# Script by Wintervenom
# https://bbs.archlinux.org/viewtopic.php?id=106367
# Forked from https://github.com/graysky2/hosts-update
# Modified by schalox

die() {
    echo "Error: $@"
    exit 1
}

(( $(id --user) )) && die "This script must be run as root"

[[ -f /etc/hosts.local ]] ||
    die "You need to create /etc/hosts.local containing the hosts you wish to keep!"

# Create the tmpfile, delete it when the script exits
tmpfile="$(mktemp)" || die "Couldn't create the tmpfile"
trap "rm --force "$tmpfile"" EXIT

curl --silent --output "$tmpfile" "http://winhelp2002.mvps.org/hosts.txt" ||
    die "Failed to download the list"

cp --force /etc/hosts.local /etc/hosts ||
    die "Couldn't replace /etc/hosts with /etc/hosts.local"

# Delete irrelevant lines and carriage returns,
# append tmpfile to /etc/hosts
awk '/^# \[Start of entries/,/^# \[end of entries/ {
        sub(/\r$/, "")
        print
    }' "$tmpfile" >> /etc/hosts || die "Couldn't append to /etc/hosts"
