#!/bin/bash
# Script by Wintervenom
# https://bbs.archlinux.org/viewtopic.php?id=106367
# Modified by schalox

if (( "$(id -u)" != 0 )); then
    echo "This script must be run as root"
    exit 1
fi

if [[ ! -f /etc/hosts.local ]]; then
    echo "You need to create /etc/hosts.local containing the hosts you wish to keep!"
    exit 1
fi

tmpfile="$(mktemp)"

curl -s --o "$tmpfile" "http://winhelp2002.mvps.org/hosts.txt"
if (( $? != 0 )) ; then
    echo "Error: Failed to download the list"
    rm -f "$tmpfile"
    exit 1
fi

# Replace /etc/hosts with /etc/hosts.local
cat /etc/hosts.local > /etc/hosts

# Delete irrelevant lines and carriage returns,
# replace every IP address with 0.0.0.0,
# append tmpfile to /etc/hosts
awk '/^# \[Start of entries/,/^# \[end of entries/ {
        sub(/\r$/, "")
        sub(/^([0-9]{1,3}\.){3}[0-9]{1,3}/, "0.0.0.0")
        print
    }' "$tmpfile" >> /etc/hosts

rm -f "$tmpfile"
